version: '3.3'
services:
  innsyn-api:
    build: ./dagpenger-innsyn-api
    ports:
      - "8080:8080"
    depends_on:
      - mockserver
    links:
      - mockserver
  oidc-provider:
    image: qlik/simple-oidc-provider
    ports:
      - 4352:4352
    environment:
      - REDIRECTS=http://localhost:443/dp-inntekt-innsyn-ui/oidc/callback
      - PORT=4352
  mockserver:
    build: ./dagpenger-innsyn-api/aktoer-mock
    ports:
      - 3050:3050
    environment:
      - PORT=3050