apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-innsyn-api
spec:
  image: repo.adeo.no:5443/dagpenger-innsyn-api:latest
  port: 8092
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 3
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
