version: '3.3'
services:
  oidc-provider:
    image: qlik/simple-oidc-provider
    ports:
      - 4352:4352
    environment:
      - REDIRECTS=http://localhost:3000/inntekter/oidc/callback
      - PORT=4352